# Generated by Django 3.2.4 on 2021-06-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name_plural': 'Каталог товаров'},
        ),
        migrations.AlterModelOptions(
            name='production',
            options={'verbose_name_plural': 'Товары'},
        ),
    ]
